using System;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class GameMenu : MonoBehaviour
{
    private static Text points, time, limit, paused;
    private float ptsMax, timeLimit;

	void Start()
    {
        points = GameObject.Find("/Canvas/Points").GetComponent<Text>();
        time = GameObject.Find("/Canvas/Time").GetComponent<Text>();
        limit = GameObject.Find("/Canvas/Limit").GetComponent<Text>();
        ptsMax = Game.MaxPoints;

        if (Game.AutoGenerated)
        {
            Destroy(limit);
            Destroy(GameObject.Find("/Canvas/Retry").gameObject);

            timeLimit = Game.MaxPoints * 2;
            limit.text = "Limit:  " + String.Format("{0:F1}", timeLimit);
        }
        else
        {
            timeLimit = Game.TimeLimit;
            limit.text = "Limit:  " + String.Format("{0:F1}", timeLimit);
        }

        GameObject soundObject = GameObject.Find("/Music");
        AudioSource audioSource = soundObject.GetComponent<AudioSource>();
        audioSource.mute = ! SettingsMenu.SoundEnabled;
	}

    void LateUpdate()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            MenuClick();
        }

        points.text = "Points: " + Game.Points + "/" + ptsMax;
        time.text = String.Format("Time:  {0:F1}", Time.timeSinceLevelLoad);

        if (Time.timeSinceLevelLoad >= timeLimit)
        {
            RetryMenu.PrevLevel = SceneManager.GetActiveScene().name;
            RetryMenu.Message = "Too slow";
            SceneManager.LoadScene("RetryScreen", LoadSceneMode.Single);
        }
    }
	
	public void MenuClick()
    {
        SceneManager.LoadScene("MainMenu", LoadSceneMode.Single);
	}

    public void RetryClick()
    {
        Game.RetryLevel();
    }

    public void ExitClick()
    {
        Application.Quit();
    }
}
